### PR TITLE
Add OnSendToSubscriber Event Hooks

### PR DESCRIPTION
**Pull request by leijux**
See https://github.com/mochi-mqtt/server/issues/377

### CODE REVIEW

**Comment by werbenhu** [comment]
Would merging the onAclCheck method and OnSendToSubscriber into one make it cleaner and tidier? Just need to modify the parameters of onAclCheck. 
Change
 ```go
func (h *HookBase) OnACLCheck(cl *Client, topic string, write bool) bool
```` 
to 
```go
func (h *HookBase) OnACLCheck(cl *Client, pk packets.Packet, write bool) bool
````

**Comment by werbenhu** [comment]
If we directly modify the parameters of `OnACLCheck`, won't it affect compatibility with older versions? @mochi-co @thedevop , what are your thoughts on this?

**Comment by thedevop** [comment]
> If we directly modify the parameters of `OnACLCheck`, won't it affect compatibility with older versions? @mochi-co @thedevop , what are your thoughts on this?

I do like merging this into OnACLCheck, in addition to the benefits you outlined, it is also a bit more performant, as hooks are not "free".

Note, this capability is only usable for embedded use case as current auth hook doesn't provide mechanism to examine packet.

**Comment by mochi-co** [comment]
@werbenhu @thedevop @leijux I'm also in favour of changing the signature of OnACLCheck, as we will otherwise be creating significant duplicated functionality. However, it will be a breaking change to OnACLCheck (and server references and tests), so I recommend opening a new PR which specifically targets this method.

**Comment by leijux** [comment]
@mochi-co @werbenhu @thedevop  Thank you everyone for your opinions. I agree very much with merging into OnACLCheck. I will close this PR and try to merge into OnACLCheck and submit a new PR.

**Comment by leijux** [comment]
@mochi-co @werbenhu @thedevop  Thank you everyone for your opinions. I agree very much with merging into OnACLCheck. I will close this PR and try to merge into OnACLCheck and submit a new PR.

**Pull request closed without merging**
